### PR TITLE
Update jsonnet to 0.16

### PR DESCRIPTION
**Pull request by tomwilkie**
Signed-off-by: Tom Wilkie <tom.wilkie@gmail.com>

### CODE REVIEW

**Comment by metalmatze** [comment]
Maybe let's remove `vendor/` first and then update? :)

**Comment by tomwilkie** [comment]
Fixes #21

**Comment by metalmatze** [comment]
Nice!

**Comment by paulfantom** [comment]
What do you think about bumping this dependency to an even newer version? There are significant performance improvements in later revisions.

We had a discussion about such bump in kube-prometheus project at https://github.com/prometheus-operator/kube-prometheus/pull/608

**Pull request merged**
